[build-system]
requires = ["setuptools>=34.4", "wheel"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_variable = ["harlow/__init__.py:__version__"]
branch = "master"

[tool.coverage.run]
source = ["harlow"]
