name: build-sphinx-docs

# Only run for master
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out your repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python39
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install package with docs dependencies
        run: |
          pip install .[docs]

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sphinx-build -b html "./docs/source" "./docs"
